{{- $name := include "infinispan-helm-charts.name" . }}
{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1/Certificate") .Values.deploy.ssl.certmanager.endpoint.enabled .Values.deploy.ssl.certmanager.endpoint.keystorePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-endpoint-keystore-password" $name }}
  annotations:
    {{- include "infinispan-helm-charts.annotations" . | nindent 4 }}
  labels:
    app: infinispan-cert-keystore
    {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.deploy.ssl.certmanager.endpoint.keystorePassword | quote }}
{{- end }}
---
{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1/Certificate") .Values.deploy.ssl.certmanager.transport.enabled .Values.deploy.ssl.certmanager.transport.keystorePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-transport-keystore-password" $name }}
  annotations:
    {{- include "infinispan-helm-charts.annotations" . | nindent 4 }}
  labels:
    app: infinispan-cert-keystore
    {{- include "infinispan-helm-charts.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.deploy.ssl.certmanager.transport.keystorePassword | quote }}
{{- end }}
